# Generated by Django 5.0.4 on 2024-04-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_address', models.CharField(max_length=64)),
                ('client_address', models.CharField(max_length=64)),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_count', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
