# Generated by Django 5.0.4 on 2024-05-09 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_options_claim_created_claim_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
