# Generated by Django 5.0.4 on 2024-08-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0003_alter_claim_created_alter_claim_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="client_address",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="claim",
            name="consultant_address",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="claim",
            name="description",
            field=models.CharField(max_length=150),
        ),
    ]
